# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180220_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to=main.models.get_image_path),
        ),
    ]
