# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='', upload_to=main.models.get_image_path),
            preserve_default=False,
        ),
    ]
