# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projects_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='posted',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
