# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180220_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(db_index=True, max_length=100), max_length=100, verbose_name='Project slug'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=models.CharField(db_index=True, max_length=100), max_length=100, verbose_name='Category slug'),
        ),
    ]
