# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180220_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
